name: Regression testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  regression_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Hello World repository
      run: ${{ secrets.QA_REPO_ACCESS_URL }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Run Maven version
      run: mvn --version
