name: Regression testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  regression_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Hello World repository
      run: git clone https://github.com/octocat/Hello-World.git

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        - with:
          - distribution: 'oracle' # See 'Supported distributions' for available options
          - java-version: '21'
      - run: java HelloWorldApp.java